更新部署文件

diff --git a/blog b/blog
--- a/blog
+++ b/blog
@@ -3,15 +3,22 @@ git pull
 mvn clean compile flyway:migrate -Pprod
 mvn clean compile -DskipTests package
 pid=$(ps aux | grep "blog" | grep -v grep | awk '{print $2}')
-echo "kill -9 $pid"
-kill -9 $pid
-STATUS=$?
-if [ $STATUS -eq 0 ]
+if [ $pid -eq "" ]
 then
-	echo "Kill previous process successfully."
-	echo "Begin restart community"
-	nohup java -jar -Dspring.profiles.active=prod target/markblog-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &
-	echo "Community restart successfully."
+    echo "Begin start blog"
+    nohup java -jar -Dspring.profiles.active=prod target/markblog-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &
+    echo "blog start successfully"
 else
-	echo "Kill previous process failed."
+    echo "kill -9 $pid"
+    kill -9 $pid
+    STATUS=$?
+    if [ $STATUS -eq 0 ]
+    then
+        echo "Kill previous process successfully."
+        echo "Begin restart blog"
+        nohup java -jar -Dspring.profiles.active=prod target/markblog-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &
+        echo "blog restart successfully."
+    else
+        echo "Kill previous process failed."
+    fi
 fi
